### ISSUE TITLE
the generate compose file is not generating with latest content off the pipeline

### ISSUE THREAD

**Issue by bicschneider** [Praqma/jenkins.praqma.com#14]
It is missing my mounted localtime...

My commit: 
https://github.com/Praqma/jenkins.praqma.com/commit/ca22e82dbe012e0ec91a41be4d57242504fcb736#diff-0

The generated yml:
http://10.10.1.110:8080/job/jenkins_as_a_code-pipeline/4/artifact/docker-compose.yml/*view*/
```
services:
  jmaster:
    image: localhost:5000/reference/jmaster:0.0.1-80-gca22e82
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
    - /home/praqma/jenkins-backup/jobs:/var/jenkins_home/jobs
    - /home/praqma/.ssh:/var/jenkins_home/.ssh
  jslave:
    image: localhost:5000/reference/jslave:0.0.1-80-gca22e82
    volumes:
    - /var/lib/docker:/var/lib/docker
    - /var/run/docker.sock:/var/run/docker.sock
    - /home/praqma/jenkins-backup/slave/gradle:/root/.gradle
  registry:
    image: registry:2.4.0
    ports:
    - 5000:5000
    volumes:
    - /home/praqma/jenkins-backup/registry:/var/lib/registry
version: '2'
```
